# Part of the code is generated by ChatGPT 5.1 model to practice prompt engineering, I will list them below
# - catch the print output from source code & analysis the output

import re

import numpy as np

import src.lab_i as lab_i


def test_lab_i_program_output(capsys, monkeypatch):
    if hasattr(lab_i, "plt"):
        monkeypatch.setattr(lab_i.plt, "show", lambda: None)

    lab_i.main()

    output = capsys.readouterr().out

    sample_match = re.search(r"Loaded signal with\s+(\d+)\s+samples", output)

    peak_match = re.search(r"Number of peaks detected:\s*(\d+)", output)

    assert sample_match is not None, "no sample number output"
    assert peak_match is not None, "no peak number output"

    num_samples = int(sample_match.group(1))
    num_peaks = int(peak_match.group(1))

    assert num_samples == 128458
    assert num_peaks == 256

    location_match = re.search(
        r"Peak locations \(indices\):\s*\[([\s\S]*?)\]",
        output,
    )

    assert location_match is not None, "没有找到 Peak locations 输出"

    peak_locations = np.fromstring(
        location_match.group(1),
        sep=" ",
        dtype=int,
    )

    assert len(peak_locations) == num_peaks

    expected_first_five = np.array([497, 1003, 1511, 2002, 2487])

    np.testing.assert_array_equal(
        peak_locations[:5],
        expected_first_five,
    )

    assert peak_locations[0] >= 0
    assert peak_locations[-1] < num_samples
    assert np.all(np.diff(peak_locations) > 0)
