import json
import pathlib
from os.path import join as pjoin


def MazeInputError(Exception):
    pass


def set_address(filename):
    script_folder = pathlib.Path(__file__).parent.resolve()
    data_dir = pjoin(script_folder, "../", "data")
    return pjoin(data_dir, filename)


directions = ["N", "E", "S", "W"]

move_map = {
    "N": (-1, 0),
    "E": (0, 1),
    "S": (1, 0),
    "W": (0, -1),
}


def turn_left(direction):
    return directions[(directions.index(direction) - 1) % 4]


def turn_right(direction):
    return directions[(directions.index(direction) + 1) % 4]


def load_maze(filename="maze.txt"):
    fname = set_address(filename)

    with open(fname) as f:
        lines = f.readlines()

    data = []
    for line in lines:
        data.append(line.split())

    return data


def find_position(maze, target):
    for x in range(len(maze)):
        for y in range(len(maze[x])):
            if maze[x][y] == target:
                return x, y

    raise MazeInputError("boom")


def move_position(pos, direction):
    x, y = pos
    dx, dy = move_map[direction]
    return x + dx, y + dy


def is_walkable(maze, pos):
    x, y = pos
    return maze[x][y] != "W"


def get_cell(maze, pos):
    x, y = pos
    return maze[x][y]


def direction_between(pos1, pos2):
    x1, y1 = pos1
    x2, y2 = pos2

    dx = x2 - x1
    dy = y2 - y1

    for direction, step in move_map.items():
        if step == (dx, dy):
            return direction

    raise ValueError("Positions are not next to each other")


def solve_maze(maze, debug=False):
    start = find_position(maze, "T")
    find_position(maze, "M")

    pos = start
    direction = "S"

    visited = {pos}
    route_stack = [pos]
    result_directions = []

    # part of the code in this loop is generated by Chatgpt, because i really cant figure out how to solve self looping
    while get_cell(maze, pos) != "D":
        if debug:
            print(f"pos={pos}, cell={get_cell(maze, pos)}, direction={direction}")

        moved = False

        choices = [
            turn_left(direction),
            direction,
            turn_right(direction),
            turn_right(turn_right(direction)),
        ]

        for new_direction in choices:
            next_pos = move_position(pos, new_direction)

            if is_walkable(maze, next_pos) and next_pos not in visited:
                direction = new_direction
                pos = next_pos

                visited.add(pos)
                route_stack.append(pos)
                result_directions.append(direction)

                if debug:
                    print(f"move {direction}, land={pos}, cell={get_cell(maze, pos)}")

                moved = True
                break

        if not moved:
            route_stack.pop()
            previous_pos = route_stack[-1]

            direction = direction_between(pos, previous_pos)
            pos = previous_pos
            result_directions.append(direction)

            if debug:
                print(f"return {direction}, land={pos}, cell={get_cell(maze, pos)}")

    return {
        "theseus_start": list(start),
        "left_steps": len(result_directions),
        "directions": result_directions,
    }


def main():
    maze = load_maze("maze.txt")
    answer = solve_maze(maze, debug=True)

    output_file = "maze_solution.json"

    with open(output_file, "w") as f:
        json.dump(answer, f, indent=4)

    print(answer)


if __name__ == "__main__":
    main()
